name: Build, Test and Deploy API (PROD)

on:
  push:
    branches: [master]

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --verbosity normal
      - uses: microsoft/variable-substitution@v1 
        with:
          files: './src/Aarhusvandsportscenter.Api/appsettings.json'
        env:
          ConnectionStrings.DbConnection: ${{ secrets.DBCONNSTR_PROD }}
          Authorization.Issuer: "https://aarhusvandsportscenter.dk/api"
          Authorization.Audience: "https://aarhusvandsportscenter.dk/api"
          SendGrid.RentalCancellationLink: "https://aarhusvandsportscenter.dk/booking/aflys/{id}"
          SendGrid.RentalFinishLink: "https://aarhusvandsportscenter.dk/booking/done/{id}/{phone}"
          SendGrid.ResetPasswordLink": "https://aarhusvandsportscenter.dk/opdater-adganskode?passwordToken={passwordToken}"
      - name: Publish Release
        run: dotnet publish ./src/Aarhusvandsportscenter.Api/ --runtime win-x86 --self-contained true -c Release
      - name: Kill application (http request)
        continue-on-error: true
        uses: fjogeleit/http-request-action@master
        with:
          url: https://aarhusvandsportscenter.dk/api/v1/System/kill?graceful=true
          method: GET
          contentType: application/json
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          exclude: wwwroot/images/contentPages/**
            - frontend/**
          local-dir: ./src/Aarhusvandsportscenter.Api/bin/Release/net5.0/win-x86/publish/
          server-dir: /public_html/
